import{A as L,a as p,S as b,N as h,K as E,i as g}from"./assets/vendor-CH0W8ZD8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".modal-header"),o=document.querySelector(".modal-btn-close"),s=document.querySelector(".header-icon-burger"),n=document.querySelectorAll(".menu-list a"),t=document.querySelector(".button-order-project"),r=document.querySelector(".btn-menu"),c=document.querySelector(".menu-center-open"),f=document.querySelector(".menu-center-list");function w(){e.classList.add("is-open"),document.body.style.overflow="hidden",o.style.display="flex"}function a(){e.classList.remove("is-open"),document.body.style.overflow=""}o.addEventListener("click",a),s.addEventListener("click",w),t.addEventListener("click",a),r.addEventListener("click",a),n.forEach(function(u){u.addEventListener("click",function(){a()})}),document.querySelectorAll(".menu-center-item a").forEach(function(u){u.addEventListener("click",function(H){f.classList.remove("is-open")})}),c.addEventListener("click",function(){f.classList.toggle("is-open")})});new L("#faq .accordion-container",{duration:600,showMultiple:!0});p.defaults.baseURL="https://portfolio-js.b.goit.study";async function M(){return(await p.get("/api/reviews")).data}async function S({email:e,comment:o}){return(await p.post("/api/requests",{email:e,comment:o})).data}function C({_id:e,author:o,avatar_url:s,review:n}){return`
  <li class="swiper-slide">
    <img
     src="${s}"
      alt="Reviewer ${e} photo"
      loading="lazy">
    <h3 class="reviewer-name">${o}</h3>
    <p class="review">
      ${n}
    </p>
  </li>
  `}function q(e){return e.map(C).join("")}function O({sectionId:e,useNavigation:o,additionalParams:s=null}){const n={direction:"horizontal",allowTouchMove:!0,keyboard:{enabled:!0,onlyInViewport:!0},...s};n.modules=[h,E],n.navigation={prevEl:".swiper-button-prev",nextEl:".swiper-button-next"},new b(`#${e} .swiper`,n)}const P={position:"topCenter",pauseOnHover:!0,closeOnClick:!0,icon:"",close:!1,timeout:2e3};function v(e){g.error({message:e,progressBarColor:"#b51b1b",title:"Error",...P})}const i=document.querySelector("#reviews .swiper-wrapper"),k={root:null,rootMargin:"0px",threshold:0},y=new IntersectionObserver(R,k);I();async function I(){await N()?O({sectionId:"reviews",useNavigation:!0,additionalParams:{spaceBetween:16,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}}}}):(document.querySelector("#reviews .side-arrows").classList.add("visually-hidden"),i.style="justify-content: center",y.observe(i))}async function N(){try{const e=await M();return i.innerHTML=q(e),!0}catch{return i.innerHTML='<li class="swiper-slide">Not found</li>',!1}}function R(e){for(const o of e)if(o.target==i&&o.isIntersecting){y.unobserve(i),v("Can't load reviews :(");return}}const m=document.querySelector(".form-cooperation"),l=document.querySelector(".js-cooperation-modal-backdrop"),T=[...l.children[0].children],j=(e,o)=>{let s,n;T.forEach(t=>{t.classList.contains("cooperative-modal__title")?s=t:t.classList.contains("cooperative-modal__comment")&&(n=t)}),s.innerHTML=e,n.innerHTML=o},d=e=>{(e.target.hasAttribute("close")||e.key==="Escape")&&(l.classList.remove("is-open"),modalEL.removeEventListener("click",d),document.removeEventListener("keydown",d))},x=async e=>{try{e.preventDefault();const{userEmail:o,userComment:s}=m,n={email:o.value.trim(),comment:s.value.trim()},{title:t,message:r}=await S(n);j(t,r),l.classList.add("is-open"),l.addEventListener("click",d),document.addEventListener("keydown",d),m.reset()}catch{v("Something was wrong! Please try again")}};m.addEventListener("submit",x);
//# sourceMappingURL=index.js.map
