import{A as m,a as d,S as w,N as v,K as y,i as b}from"./assets/vendor-CH0W8ZD8.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".modal-header"),n=document.querySelector(".modal-btn-close"),s=document.querySelector(".header-icon-burger"),o=document.querySelectorAll(".menu-list a"),t=document.querySelector(".button-order-project"),r=document.querySelector(".btn-menu"),c=document.querySelector(".menu-center-open"),u=document.querySelector(".menu-center-list");function f(){e.classList.add("is-open"),document.body.style.overflow="hidden",n.style.display="flex"}function a(){e.classList.remove("is-open"),document.body.style.overflow=""}n.addEventListener("click",a),s.addEventListener("click",f),t.addEventListener("click",a),r.addEventListener("click",a),o.forEach(function(l){l.addEventListener("click",function(){a()})}),document.querySelectorAll(".menu-center-item a").forEach(function(l){l.addEventListener("click",function(N){u.classList.remove("is-open")})}),c.addEventListener("click",function(){u.classList.toggle("is-open")})});new m("#faq .accordion-container",{duration:600,showMultiple:!0});d.defaults.baseURL="https://portfolio-js.b.goit.study";async function h(){return(await d.get("/api/reviews")).data}function L({_id:e,author:n,avatar_url:s,review:o}){return`
  <li class="swiper-slide">
    <img
     src="${s}"
      alt="Reviewer ${e} photo"
      loading="lazy">
    <h3 class="reviewer-name">${n}</h3>
    <p class="review">
      ${o}
    </p>
  </li>
  `}function g(e){return e.map(L).join("")}function E({sectionId:e,useNavigation:n,additionalParams:s=null}){const o={direction:"horizontal",allowTouchMove:!0,keyboard:{enabled:!0,onlyInViewport:!0},...s};o.modules=[v,y],o.navigation={prevEl:".swiper-button-prev",nextEl:".swiper-button-next"},new w(`#${e} .swiper`,o)}const O={position:"topCenter",pauseOnHover:!0,closeOnClick:!0,icon:"",close:!1,timeout:2e3};function S(e){b.error({message:e,progressBarColor:"#b51b1b",title:"Error",...O})}const i=document.querySelector("#reviews .swiper-wrapper"),q={root:null,rootMargin:"0px",threshold:0},p=new IntersectionObserver(C,q);P();async function P(){await M()?E({sectionId:"reviews",useNavigation:!0,additionalParams:{spaceBetween:16,breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}}}}):(document.querySelector("#reviews .side-arrows").classList.add("visually-hidden"),i.style="justify-content: center",p.observe(i))}async function M(){try{const e=await h();return i.innerHTML=g(e),!0}catch{return i.innerHTML='<li class="swiper-slide">Not found</li>',!1}}function C(e){for(const n of e)if(n.target==i&&n.isIntersecting){p.unobserve(i),S("Can't load reviews :(");return}}
//# sourceMappingURL=index.js.map
